### PR TITLE
Adapt repo code to work with OpenShift

### PR DESCRIPTION
**Pull request by gvassallo**

### CODE REVIEW

**Comment by gvassallo** [comment]
> why do these need to be build args?

Because I wanna have it generic so that you can configure the docker build using the git server you want

**Comment by andreaseger** [comment]
> > why do these need to be build args?
> 
> Because I wanna have it generic so that you can configure the docker build using the git server you want

Hmm but it's nothing the build itself needs. So why not simply overwrite this in the cron job as env variable

**Comment by gvassallo** [comment]
> > > why do these need to be build args?
> > 
> > 
> > Because I wanna have it generic so that you can configure the docker build using the git server you want
> 
> Hmm but it's nothing the build itself needs. So why not simply overwrite this in the cron job as env variable

It actually does need it. If you don't do that, it will try to add the key for the git server when cloning the repo and fail since interaction is required

**Comment by andreaseger** [comment]
> > > > why do these need to be build args?
> > > 
> > > 
> > > Because I wanna have it generic so that you can configure the docker build using the git server you want
> > 
> > 
> > Hmm but it's nothing the build itself needs. So why not simply overwrite this in the cron job as env variable
> 
> It actually does need it. If you don't do that, it will try to add the key for the git server when cloning the repo and fail since interaction is required

Ah the keyscan thing needs it. missed that

**Review by nilsding — APPROVED** [review]
Looks good to me overall.

**Review by kmpzr — APPROVED** [review]

**Review by andreaseger — APPROVED** [review]

**Pull request merged**
